# Hello World

In [192]:
import numpy as np

In [193]:
a= np.array([1,2,3,0.4] ,dtype='float64')
print(a)


[1.  2.  3.  0.4]


In [194]:
b= np.array([[1,2,3],[4,3,5]])
print(b)

[[1 2 3]
 [4 3 5]]


In [195]:
#Get Dimension
a.ndim

1

In [196]:
# Get Dimension
b.ndim

2

In [197]:
# Get Shape
a.shape

(4,)

In [198]:
# Get type
a.dtype

dtype('float64')

In [199]:
b.dtype

dtype('int32')

In [200]:
# Get Size
a.itemsize

8

In [201]:
# Get Size
b.itemsize

4

In [202]:
# Get TotalSize
b.size

6

# Accessing / Changing Specific Elements

In [203]:
a  = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [204]:
# Get a specific Element[r,c]
a[1,5]

13

In [205]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [206]:
# Get a specific col
a[:,2]

array([ 3, 10])

In [207]:
# Get a little more fancy[startindex:endindex:stepsize]
a[0, 1: -1 : 2]

array([2, 4, 6])

In [208]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [209]:
a[: ,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# 3D Examples :

## initializing diffrent types of array

In [210]:
# All zeros matrix
c = np.zeros((2,3,3))
c

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [211]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [212]:
np.full(a.shape,4)
# or
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

##### random decimal numbers

In [213]:
np.random.random_sample(a.shape)

array([[0.4790913 , 0.53206581, 0.26481794, 0.08106062, 0.36269238,
        0.3177928 , 0.61815763],
       [0.53486012, 0.65072615, 0.47687549, 0.05920984, 0.16053436,
        0.17650634, 0.09531661]])

In [214]:
np.random.rand(3,5)

array([[0.48147025, 0.51257153, 0.30820209, 0.20091166, 0.32431336],
       [0.89052727, 0.22177752, 0.77470566, 0.06198429, 0.91700143],
       [0.56072247, 0.10626856, 0.00298098, 0.19256433, 0.92040297]])

In [215]:
# random integer values
np.random.randint(7, size=(4,3))

array([[2, 1, 5],
       [4, 1, 1],
       [4, 1, 3],
       [5, 3, 4]])

In [216]:
np.random.randint(-4,9, size=(4,3))

array([[ 6, -3,  3],
       [ 1,  2, -3],
       [ 4, -4, -2],
       [ 0, -3,  3]])

In [217]:
# the identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Mathmatics

In [218]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [219]:
a+2
print(a)

[1 2 3 4]


In [220]:
a-2

array([-1,  0,  1,  2])

In [221]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [222]:
b = np.array([1,0,2,1])
a + b

array([2, 2, 5, 5])

In [223]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [224]:
np.cos(b)

array([ 0.54030231,  1.        , -0.41614684,  0.54030231])

## Liner Algebra

In [225]:
a = np.ones((2,3))
print(a)
print("_____________")
b = np.full((3,2) , 3)
print(b)
print("_____________")
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
_____________
[[3 3]
 [3 3]
 [3 3]]
_____________


array([[9., 9.],
       [9., 9.]])

In [226]:
c = np.identity(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [227]:
# find the determinate
np.linalg.det(c)

1.0

In [228]:
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix norm
# Inverse
#....

## Recognizing Array

In [229]:
before = np.array([[1,2,3,4],[4,5,6,7]])
print(before)

[[1 2 3 4]
 [4 5 6 7]]


In [230]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [ ]:
# vertically stocking vectors
v1 = np.array([1,3,2,4])
v2 = np.array([6,7,8,5])
np.vstack([v1,v2,v2,v1])

In [ ]:
h1 = np.zeros((1,2))
h2 = np.ones((2,2))

np.hstack(h1,h2)


## Miscellaenous

In [242]:
filedata = np.loadtxt('data.txt', dtype=str)
# filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

FileNotFoundError: data.txt not found.